# Generated by Django 3.1.4 on 2020-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=12)),
                ('speed_data', models.IntegerField(default=0)),
                ('speed_target', models.IntegerField(default=0)),
                ('duty', models.IntegerField(default=0)),
                ('mode', models.IntegerField(choices=[(0, 'Off'), (1, 'On'), (2, 'Err'), (3, 'Discon')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12)),
                ('speed', models.IntegerField(default=0)),
                ('duty', models.IntegerField(default=0)),
            ],
        ),
    ]
