# Generated by Django 3.1.4 on 2020-12-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='id',
        ),
        migrations.AlterField(
            model_name='controller',
            name='mac',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
