# Generated by Django 3.1.4 on 2020-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_auto_20201220_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='id_num',
            field=models.IntegerField(default=-1),
        ),
    ]
