# Generated by Django 3.1.4 on 2020-12-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_controller_id_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='id_num',
        ),
    ]
