# Generated by Django 3.1.4 on 2020-12-20 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0004_remove_controller_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='updated_last',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 14, 11, 27, 287849), verbose_name='date updated'),
            preserve_default=False,
        ),
    ]
