# Generated by Django 3.1.4 on 2020-12-20 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0005_controller_updated_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 15, 6, 35, 357344, tzinfo=utc), verbose_name='date updated'),
            preserve_default=False,
        ),
    ]
