# Generated by Django 3.1.4 on 2020-12-20 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0006_data_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='controlled_last',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 23, 47, 4, 527057, tzinfo=utc), verbose_name='controlled updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controller',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On'), (2, 'Err'), (3, 'Discon')], default=3),
        ),
    ]
